version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-
      - run:
          name: "Install Dependencies"
          command: |
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: "Setup"
          command: mkdir -p $TEST_RESULTS/go-test
      - run:
          name: "Run Tests"
          command: go test -v 2>&1 | tee >(go-junit-report > $TEST_RESULTS/go-test/report.xml)
      - save_cache:
          key: go-mod-v1-
          paths:
            - "/go/pkg/mod"
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
